name: ubuntu-image
summary: Create Ubuntu images
description: |
  Use this tool to create Ubuntu images.
version: 0.15+snap4
grade: stable
confinement: classic

apps:
  ubuntu-image:
    command: bin/ubuntu-image

environment:
  PATH: $SNAP/bin/:$PATH
  PYTHONPATH: $SNAP/lib/python3.5/site-packages:$PYTHONPATH

parts:
  ubuntu-image:
    plugin: python
    source: https://github.com/CanonicalLtd/ubuntu-image.git
    source-type: git
    python-packages:
      - PyYAML
      - attrs
      - voluptuous
    prime:
      - bin/ubuntu-image
      - usr
      - lib
      - sbin
    stage-packages:
      - e2fsprogs
      - mtools
      - python3-debian
      - python3-parted
      - util-linux
    install: |
      cp -a ../install/usr/lib/python3/dist-packages/parted ../stage/lib/python3.5/site-packages
      cp -a ../install/usr/lib/python3/dist-packages/pyparted-*.egg-info ../stage/lib/python3.5/site-packages
  snapd:
    plugin: go
    source: https://github.com/snapcore/snapd
    source-type: git
    go-importpath: github.com/snapcore/snapd
    prime:
      - bin/snap
