name: ubuntu-image
summary: Create Ubuntu images
description: |
  Use this tool to create Ubuntu images.
version: 1.0+snap4
grade: stable
confinement: classic

environment:
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH
  PYTHONPATH: $SNAP/lib/python3/site-packages:$PYTHONPATH
  LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/lib

apps:
  ubuntu-image:
    command: bin/ubuntu-image

parts:
  ubuntu-image:
    plugin: python
    source: .
    python-packages:
      - PyYAML
      - attrs
      - voluptuous
    prime:
      - bin/ubuntu-image
      - usr
      - lib
      - sbin
    stage-packages:
      - coreutils
      - dosfstools
      - e2fsprogs
      - fakeroot
      - mtools
      - python3-debian
      - python3-parted
      - util-linux
    install: |
      TRIPLET="$(uname -p)-linux-gnu"
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/$TRIPLET/* $SNAPCRAFT_PART_INSTALL/usr/lib/
      mv $SNAPCRAFT_PART_INSTALL/lib/$TRIPLET/* $SNAPCRAFT_PART_INSTALL/lib/
      cd $SNAPCRAFT_PART_INSTALL/lib/
      mkdir python3
      mv python3.*/* python3/
