name: echo-service
version: '0.2'
summary: Echo service for image boot test
description: |
  LP: #1625732 - an autopkgtest boot test.  This snap is loaded into an image
  created by ubuntu-image using --extra-snaps.  It implements an echo service
  which starts on boot and which the autopkgtest pings once the image is
  booted.  If it connects and returns the expected results, the test passes.
grade: devel
confinement: strict
apps:
  echo-service:
    command: python3 -m echo
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
parts:
  echo-service:
    plugin: python
    source: ./echo
