name: echo-service
version: '0.6'
summary: Echo service for image boot test
description: |
  LP: #1625732 - an autopkgtest boot test.  This snap is loaded into an image
  created by ubuntu-image using --extra-snaps.  It implements an echo service
  which starts on boot and which the autopkgtest pings once the image is
  booted.  If it connects and returns the expected results, the test passes.
grade: devel
confinement: devmode
apps:
  echo-service:
    command: ncat -l 8888 --keep-open --exec "/bin/cat"
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
parts:
  echo-service:
    plugin: dump
    stage-packages: ['nmap', 'coreutils', 'liblua5.3-0']
    stage: ['usr/bin/ncat', 'bin/cat', 'usr/lib']
